### ISSUE TITLE
Password Generator

### ISSUE THREAD

**Issue by vefoto-gates** [vefoto-gates/PasswordGenerator#1]
I want a Password Generator That Generates Password for Users like Lastpass or 1Pass, etc.

**Comment by gauravmandall** [comment]
I just Developed a Password Generator as per Guidelines in CONTRIBUTING.MD using Python
I made this Right please merge my pull request

**Comment by sambhavgupta0705** [comment]
Hey I want to work on this issue, I can make it in Javascript or python
Please assign this issue to me

**Comment by vefoto-gates** [comment]
Hey @sambhavgupta0705 The first pull request is generated by @gauravmandall but you can also make it and generate a pull request.

**Comment by sambhavgupta0705** [comment]
Ok thanks

**Comment by sambhavgupta0705** [comment]
Hey do I need to code in python only or can I code in js  or cpp also

**Comment by Ansh-Sarkar** [comment]
Hey ! A few proposals from my side : 

- [x] ```refactor:``` Was thinking about refactoring the directory structure a with codes of every language inside respective folders.
- [x] ```feat:``` Adding a **Typescript** version of the random password generator
- [x] ```feat:``` Adding a **Rust** version of the random password generator

Do let me know if you feel that these proposals would be a valuable contribution to the repository. I'll start working on them immediately. Thanks !

**Comment by vefoto-gates** [comment]
alright @Ansh-Sarkar Great Job

**Comment by vefoto-gates** [comment]
hey your proposals would be helpful to others
make it happen

**Comment by vefoto-gates** [comment]
Now the contribution is over. 
Thanks to everyone for contributing to this repository.

If you enjoyed it, please give it a star.
